djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
#from django.contrib.auth import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('', include('mysite.urls')),
]

mysite/urls.py
from django.urls import path
from . import views
from django.conf.urls import include


urlpatterns = [
    path("categories/", views.CategoryView.as_view(), name='index'),
    path("brands_with_description/", views.BrandView.as_view(), name="brands_with_description"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("register/", views.register, name="register"),
    path("accounts/", include("django.contrib.auth.urls"))
]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [
    path('<int:pk>/', views.ProdeuctDetailView.as_view(), name='detail'),
#    path('<int:pk>/', views.ProductDetailFormView.as_view(), name='detail'),
    path('<int:pk>/add_to_cart', views.add_to_cart, name='add_to_cart'),
    path('', views.ProductListView.as_view()),
]

product/models.py
from django.db import models
from django.conf import settings
from mysite.models import Category, Brand

class Product(models.Model):
    #past method with short name  str__
    # list display
    description = models.TextField()
    short_description = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    brand = models.ForeignKey(
        Brand,
        on_delete=models.CASCADE
    )
    is_pesent = models.BooleanField(default=True)

    def __str__(self):
        return self.short_description


class Review(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        default=1
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )
    rating = models.SmallIntegerField()
    timestamp = models.DateTimeField()
    text = models.TextField()

    def __str__(self):
        return self.product

product/forms.py
from django import forms

class CartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1)

product/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Product
from order.models import ProductInOrder, Order
from django.utils import timezone
from .forms import CartForm

class ProductListView(generic.ListView):
    template_name = 'product/products.html'
    context_object_name = 'product_list'

    def get_queryset(self):
        return Product.objects.all()


class ProductListViewByCategory(generic.ListView):
    template_name = 'product/products_by_category.html'
    model = Product


class ProdeuctDetailView(generic.DetailView):
    model = Product
    template_name = 'product/detail.html'
    def render_to_response(self, context, **response_kwargs):
        context["form"] = CartForm()
        return super(ProdeuctDetailView, self).render_to_response(context, **response_kwargs)

def add_to_cart(request, pk):

    if request.user.is_authenticated:

        if request.method == "POST":
            product = get_object_or_404(Product, pk=pk)
            form = CartForm(request.POST)
            if form.is_valid():
                order = Order.objects.filter(user=request.user, status=Order.NOT_PAID).last()

                if order is None:
                    print(order)
                    order = Order(user=request.user,
                                  timestamp=timezone.now())
                    order.save()
                product_in_order = ProductInOrder.objects.filter(order=order, product=product).last()

                if product_in_order is None:
                    product_in_order = ProductInOrder(
                        product=product,
                        order=order,
                        quantity=1
                    )
                    product_in_order.save()
                else:
                    product_in_order.quantity += form.cleaned_data['quantity']
                    product_in_order.save()
                return HttpResponseRedirect(reverse('product:detail', args=(product.pk,)))
            else:
#todo add error message if qantity <= 0 переделать форму и добавить ошибку
                context = {'form': form, 'product':product}
               # return HttpResponseRedirect(reverse('product:detail', args=(product.pk, )))
                return render(request, 'product/detail.html', context)
    else:
        return HttpResponseRedirect(reverse('login'))

templates/product/detail.html
Hello, {{ user.email|default:'Guest' }}!

<h1>{{ product.category }}</h1>
<h1>{{ product.short_description }}</h1>
<ul>
    {{ product.description }}
</ul>
<ul>
    {{ product.price }}
</ul>

<form method="post" action="{% url  'product:add_to_cart' product.id %}">

    {% csrf_token %}
    {{form}}
    <input type="submit" value="Add product to order" >
</form>
<ul>
    {{ zzz }}
</ul>


<li><a href="/product/">Back to product page</a></li>

templates/product/index.html
<h1>Product page</h1>
{% if product_list %}
    <ul>
    {% for product in product_list %}
        <li><a href="/product/{{ product.id }}/">{{ product.short_description }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No products are available.</p>
{% endif %}

templates/product/products.html
Hello, {{ user.email|default:'Guest' }}!

<h1>Product page</h1>
{% if product_list %}
    <ul>
    {% for product in product_list %}
        <li><a href="/product/{{ product.id }}/">{{ product.short_description }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No products are available.</p>
{% endif %}

templates/product/products_by_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>